site_name: The Engineer's Warehouse
site_url: https://seyoungnam.github.io/docs/
theme: 
  name: material
  font: 
    text: Roboto Flex
    code: Roboto Mono
  icon:
    logo: octicons/agent-16
    annotation: material/arrow-right-circle
  features:
    - navigation.footer
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: indigo
extra_css:
  - stylesheets/extra.css
plugins:
  - glightbox
  - search
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seyoungnam
    - icon: fontawesome/brands/github
      link: https://github.com/seyoungnam
copyright: Copyright &copy; 2026 Seyoung Nam

nav:
  - Home: index.md
  - Istio:
    - Snippets:
      - Traffic Redirection: istio/snippets/envoy-netfilter.md
  - Kubernetes:
    - k8s-in-action:
      - 01. Intro: kubernetes/k8s-in-action/01-intro-k8s.md
      - 02. Containers: kubernetes/k8s-in-action/02-understanding-containers.md
      - 03. First App: kubernetes/k8s-in-action/03-deploying-first-app.md
      - 04. API: kubernetes/k8s-in-action/04-navigating-the-k8s-api.md
      - 14. ReplicaSet: kubernetes/k8s-in-action/14-replicaset.md
      - 15. Deployment: kubernetes/k8s-in-action/15-deployment.md
      - 16. StatefulSet: kubernetes/k8s-in-action/16-statefulset.md
    - Networking:
      - 1. Networking Introduction: kubernetes/networking/01-networking-introduction.md
      - 2. Linux Networking: kubernetes/networking/02-linux-networking.md
      - 3. Container Networking Basics: kubernetes/networking/03-container-networking-basics.md
  - EKS:
    - EKS Provisioning:
      - Provisioning Lab: EKS/EKS Provisioning/01-deploy.md
    - Networking:
      - Networking Fundamentals: EKS/Networking/02-networking.md
      - Networking Lab 1: EKS/Networking/03-networking-lab.md
      - Networking Lab 2: EKS/Networking/04-networking-lab-2.md
      - Networking Lab 3: EKS/Networking/05-networking-lab-3.md
    - Scaling:
      - SSM, ALB, Prometheus, Grafana: EKS/Scaling/06-scaling.md
      - Node Types: EKS/Scaling/07-scaling-2.md
      - Auto Scalers: EKS/Scaling/08-scaling-3.md
      - Karpenter: EKS/Scaling/09-scaling-4.md
    - Identity & Access Management:
      - AuthN/AuthZ Fundamentals: EKS/Auth/10-auth.md
      - IAM Roles & Node Identity: EKS/Auth/11-auth-2.md
      - Access Entries & Custom RBAC: EKS/Auth/12-auth-3.md
    - Debugging:
      - Frameworks: EKS/Debugging/overview.md
      - Control Plane: EKS/Debugging/control-plane.md
      - Node: EKS/Debugging/node.md
      - Pod: EKS/Debugging/pod.md
      - Health Check: EKS/Debugging/health-check.md
      - Networking: EKS/Debugging/networking.md
      - Storage: EKS/Debugging/storage.md
      - GPU: EKS/Debugging/gpu.md
      - Auto Mode: EKS/Debugging/auto-mode.md
      - Observability: EKS/Debugging/observability.md
    - CI/CD:
      - Platform Engineering by GitOps: EKS/cicd/gitops.md
      - Lab Environment: EKS/cicd/lab-env.md
      - "Lab 1: App & Infra Blueprint": EKS/cicd/lab1-infra-arch.md
      - "Lab 2: Saas Tier Strategy": EKS/cicd/lab2-saas-tier.md
      - "Lab 3: Auto Tenant Onboarding": EKS/cicd/lab3-tenant-auto-onboard.md
    - Version Upgrades:
      - Overview: EKS/upgrade/overview.md
      - Lab Environment: EKS/upgrade/lab-env.md
      - In-place Cluster Upgrades: EKS/upgrade/in-place-upgrades.md
    - GPU Operations:
      - 1. EC2 Quota Increase Request: EKS/gpu-operations/ec2-quota.md 
      - 2. Exploring the Environment: EKS/gpu-operations/exploring-the-environment.md
      - 3. Optimizing GPU Infra: EKS/gpu-operations/optimizing-gpu-infra.md
      - 4. Deploying the model using vLLM: EKS/gpu-operations/deploying-vllm.md
      - 5. Interacting with LLM: EKS/gpu-operations/interacting-llm.md
      - 6. Setting up observability stack: EKS/gpu-operations/setup-o11y-stack.md
      - 7. Configuring NVIDIA DCGM Dashboard: EKS/gpu-operations/nvidia-dcgm-dashboard.md
      - 8. vLLM Model Monitoring: EKS/gpu-operations/vllm-model-monitoring.md
      - 9. Cleanup: EKS/gpu-operations/cleanup.md
  - Computer Systems:
    - Process vs Thread: computer-systems/process-vs-thread.md
    - Stack vs Heap: computer-systems/stack-vs-heap.md
  - Homelab:
    - Kubernetes: homelab/kubernetes.md
    - Ubuntu: homelab/ubuntu.md
    - Fedora: homelab/fedora.md
    - Dual Boot: homelab/dual-boot.md
  - Linux:
    - Snippets:
      - Permissions: linux/snippets/permissions.md
    - Linux Commands:
      - Six Commands: linux/linux-commands/01-six-commands.md
      - Introducing the Shell: linux/linux-commands/02-shell.md
      - Rerunning Commands: linux/linux-commands/03-rerun-cmd.md
  - Networking:
    - Snippets:
      - Packet delivery within the network: networking/snippets/packet-delivery-same-network.md
      - Packet delivery across the network: networking/snippets/packet-delivery-across-network.md
      - Packet delivery across multiple networks: networking/snippets/packet-delivery-multi-networks.md
    - OSI & TCP/IP: networking/01-osi-tcpip.md
    - TCP/IP: networking/02-tcpip.md
    - Routing: networking/03-routing.md
    - TCP/IP App: networking/04-tcpip-app.md
    - NAT: networking/05-nat.md

  - Golang:
    - slice-vs-array: golang/slice-vs-array.md
  - Web Frameworks:
    - Express.js:
      - Learn Express JS: web-frameworks/express-js/in-35-mins.md
  - LeetCode:
    - Arrays & hashing:
      - 217. Contains Duplicate: leetcode/arrays-hashing/217-contains-duplicate.md
      - 242. Valid Anagram: leetcode/arrays-hashing/242-valid-anagram.md
      - 1. Two Sum: leetcode/arrays-hashing/1-two-sum.md
      - 49. Group Anagrams: leetcode/arrays-hashing/49-group-anagrams.md
      - 347. Top K Frequent Elements: leetcode/arrays-hashing/347-top-k-frequent-elements.md
      - 271. Encode and Decode Strings: leetcode/arrays-hashing/271-encode-and-decode-strings.md
      - 238. Product of Array Except Self: leetcode/arrays-hashing/238-product-of-array-except-self.md
      - 937. Reorder Data in Log Files: leetcode/arrays-hashing/937-reorder-data-in-log-files.md
      - 36. Valid Sudoku: leetcode/arrays-hashing/36-valid-sudoku.md
      - 128. Longest Consecutive Sequence: leetcode/arrays-hashing/128-longest-consecutive-sequence.md
      - 146. LRU Cache: leetcode/arrays-hashing/146-lru-cache.md
    - Two Pointers:
      - 125. Valid Palindrome: leetcode/two-pointers/125-valid-palindrome.md
      - 167. Two Sum II - Input Array Is Sorted: leetcode/two-pointers/126-two-sum-ii-input-array-is-sorted.md
      - 15. 3Sum: leetcode/two-pointers/15-3sum.md
      - 11. Container With Most Water: leetcode/two-pointers/11-container-with-most-water.md
      - 42. Trapping Rain Water: leetcode/two-pointers/42-trapping-rain-water.md
    - Sliding Window:
      - 121. Best Time to Buy and Sell Stock: leetcode/sliding-window/121-best-time-to-buy-and-sell-stock.md
      - 3. Longest Substring Without Repeating Characters: leetcode/two-pointers/3-longest-substring-without-repeating-characters.md
      - 424. Longest Repeating Character Replacement: leetcode/sliding-window/424-longest-repeating-character-replacement.md
      - 567. Permutation in String: leetcode/sliding-window/567-permutation-in-string.md
      - 76. Minimum Window Substring: leetcode/sliding-window/76-minimum-window-substring.md
      - 239. Sliding Window Maximum: leetcode/sliding-window/239-sliding-window-maximum.md
    - Stack:
      - 20. Valid Parentheses: leetcode/stack/20-valid-parentheses.md
      - 155. Min Stack: leetcode/stack/155-min-stack.md
      - 150. Evaluate Reverse Polish Notation: leetcode/stack/150-evaluate-reverse-polish-notation.md
      - 739. Daily Temperatures: leetcode/stack/739-daily-temperatures.md
      # - 853. Car Fleet: leetcode/stack/853-car-fleet.md
      # - 84. Largest Rectangle in Histogram: leetcode/stack/84-largest-rectangle-in-histogram.md
    - Heap:
      - 973. K Closest Points to Origin: leetcode/heap/973-k-closest-points-to-origin.md
      - 23. Merge k Sorted Lists: leetcode/heap/23-merge-k-sorted-lists.md
      - 253. Meeting Rooms II: leetcode/heap/253-meeting-rooms-ii.md
    - Graphs:
      - 200. Number of Islands: leetcode/graphs/200-number-of-islands.md
      - 994. Rotting Oranges: leetcode/graphs/994-rotting-oranges.md
      - 127. Word Ladder: leetcode/graphs/127-word-ladder.md
    - Backtracking:
      - 78. Subsets: leetcode/backtracking/78-subsets.md
      - 90. Subsets II: leetcode/backtracking/90-subsets-2.md
      - 39. Combination Sum: leetcode/backtracking/39-combination-sum.md
      - 40. Combination Sum II: leetcode/backtracking/40-combination-sum-2.md
      - 46. Permutations: leetcode/backtracking/46-permutations.md
      - 22. Generate Parentheses: leetcode/backtracking/22-generate-parentheses.md
      - 79. Word Search: leetcode/backtracking/79-word-search.md
      - 131. Palindrome Partitioning: leetcode/backtracking/131-palindrome-partitioning.md
      - 17. Letter Combinations of a Phone Number: leetcode/backtracking/17-letter-combinations-of-a-phone-number.md
      - 51. N-Queens: leetcode/backtracking/51-n-queens.md


