site_name: The Engineer's Warehouse
site_url: https://seyoungnam.github.io/docs/
theme: 
  name: material
  font: 
    text: Roboto Flex
    code: Roboto Mono
  icon:
    logo: octicons/agent-16
    annotation: material/arrow-right-circle
  features:
    - navigation.footer
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: indigo
extra_css:
  - stylesheets/extra.css
plugins:
  - glightbox
  - search
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seyoungnam
    - icon: fontawesome/brands/github
      link: https://github.com/seyoungnam
copyright: Copyright &copy; 2026 Seyoung Nam

nav:
  - Home: index.md
  - Computer Systems:
    - Process vs Thread: computer-systems/process-vs-thread.md
  - Homelab:
    - Kubernetes: homelab/kubernetes.md
  - Linux Commands:
    - Six Commands: linux-commands/01-six-commands.md
    - Introducing the Shell: linux-commands/02-shell.md
    - Rerunning Commands: linux-commands/03-rerun-cmd.md
  - Network:
    - OSI & TCP/IP: network/01-osi-tcpip.md
    - TCP/IP: network/02-tcpip.md
    - Routing: network/03-routing.md
    - TCP/IP App: network/04-tcpip-app.md
    - NAT: network/05-nat.md
  - Kubernetes:
    - 01. Intro: kubernetes/01-intro-k8s.md
    - 02. Containers: kubernetes/02-understanding-containers.md
    - 03. First App: kubernetes/03-deploying-first-app.md
    - 04. API: kubernetes/04-navigating-the-k8s-api.md
    - 14. ReplicaSet: kubernetes/14-replicaset.md
    - 15. Deployment: kubernetes/15-deployment.md
    - 16. StatefulSet: kubernetes/16-statefulset.md
  - EKS:
    - EKS Provisioning:
      - Provisioning Lab: EKS/EKS Provisioning/01-deploy.md
    - Networking:
      - Networking Fundamentals: EKS/Networking/02-networking.md
      - Networking Lab 1: EKS/Networking/03-networking-lab.md
      - Networking Lab 2: EKS/Networking/04-networking-lab-2.md
      - Networking Lab 3: EKS/Networking/05-networking-lab-3.md
    - Scaling:
      - SSM, ALB, Prometheus, Grafana: EKS/Scaling/06-scaling.md
      - Node Types: EKS/Scaling/07-scaling-2.md
      - Auto Scalers: EKS/Scaling/08-scaling-3.md
      - Karpenter: EKS/Scaling/09-scaling-4.md
    - Identity & Access Management:
      - AuthN/AuthZ Fundamentals: EKS/Auth/10-auth.md
      - IAM Roles & Node Identity: EKS/Auth/11-auth-2.md
      - Access Entries & Custom RBAC: EKS/Auth/12-auth-3.md
    - Debugging:
      - Frameworks: EKS/Debugging/overview.md
      - Control Plane: EKS/Debugging/control-plane.md
      - Node: EKS/Debugging/node.md
      - Pod: EKS/Debugging/pod.md
      - Health Check: EKS/Debugging/health-check.md
      - Networking: EKS/Debugging/networking.md
      - Storage: EKS/Debugging/storage.md
      - GPU: EKS/Debugging/gpu.md
      - Auto Mode: EKS/Debugging/auto-mode.md
      - Observability: EKS/Debugging/observability.md
    - CI/CD:
      - Platform Engineering by GitOps: EKS/cicd/gitops.md
      - Lab Environment: EKS/cicd/lab-env.md
      - "Lab 1: App & Infra Blueprint": EKS/cicd/lab1-infra-arch.md
      - "Lab 2: Saas Tier Strategy": EKS/cicd/lab2-saas-tier.md
      - "Lab 3: Auto Tenant Onboarding": EKS/cicd/lab3-tenant-auto-onboard.md
  - LeetCode:
    - Backtracking:
      - 78. Subsets: leetcode/backtracking/78-subsets.md
      - 39. Combination Sum: leetcode/backtracking/39-combination-sum.md


